apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
  annotations:
    configmap.reloader.stakater.com/reload: {{ .Values.configmap.name }}
    secret.reloader.stakater.com/reload: test-secret
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
      tier: frontend
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        tier: frontend
    spec: # Pod spec
      containers:
      - name: mycontainer
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: {{ .Values.configmap.name }}
        env:
        - name: CUSTOM_HEADER
          valueFrom:
            secretKeyRef:
              name: test-secret
              key: CUSTOM_HEADER
        - name: STAM_TEST
          valueFrom:
            secretKeyRef:
              name: stam-test-secret
              key: STAM_TEST
