apiVersion: v1
kind: Service
metadata:
  name: {{.Values.appName }}-external
  namespace: default  # The namespace where you want to create the reference
spec:
  type: ExternalName
  externalName: myhelmappprod.prod.svc.cluster.local  # Full DNS name of the service in the 'prod' namespace
